#!/usr/bin/env bash

# Version manager: https://asdf-vm.com/#/core-manage-asdf-vm
git clone https://github.com/asdf-vm/asdf.git ~/.asdf --branch v0.7.6
echo -e '\n. $HOME/.asdf/asdf.sh' >> ~/.bash_profile
echo -e '\n. $HOME/.asdf/completions/asdf.bash' >> ~/.bash_profile

. $HOME/.asdf/asdf.sh
for lang in "elixir nodejs ruby erlang"; do
  asdf plugin-add $lang
done

ln -s $(pwd)/asdfrc ~/.asdfrc
