#!/usr/bin/env bash

# Automatically starts applications during office hours

day=$(date +"%u")
currenttime=$(date +%H:%M)

WORKING_HOURS_START="07:25"
WORKING_HOURS_END="18:30"

workapps="slack
google-chrome
thunderbird
firefox"

is_not_running() {
  local process=$(ps ax |grep $1|grep -v grep)
  test -z "$process"
}

if ((day <= 5)); then
   if [[ $currenttime > $WORKING_HOURS_START ]] && [[ $currenttime < $WORKING_HOURS_END ]]; then
     for app in $workapps
     do
       is_not_running $app && $app 2>&1 1>/dev/null &
     done
   fi
fi
