if $COLORTERM == 'gnome-terminal'
  set t_Co=256
endif
if $_system_name == 'Debian'
  set t_Co=256
endif

" ------------------------------------------
" Setting up NeoBundle
" ------------------------------------------

set nocompatible " be iMproved

if has('vim_starting')
  " Required:
  set runtimepath+=~/.vim/bundle/neobundle.vim/
endif

"-------------------------------------------
 
if has("gui_macvim")
  set guioptions-=T "if using a GUI Version
endif

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
" let Vundle manage Vundle, required
Plugin 'VundleVim/Vundle.vim'

" Rails related
Plugin 'tpope/vim-rails'
Plugin 'tpope/vim-rake'
Plugin 'thoughtbot/vim-rspec'
Plugin 'tpope/vim-bundler'
Plugin 'tpope/vim-haml'
Plugin 'vim-ruby/vim-ruby'
Plugin 'slim-template/vim-slim.git'
Plugin 'tpope/vim-endwise'
Plugin 'kchmck/vim-coffee-script'
Plugin 'ecomba/vim-ruby-refactoring'
" Workflow
Plugin 'roman/golden-ratio'
Plugin 'tomtom/tcomment_vim'
Plugin 'scrooloose/syntastic'
Plugin 'godlygeek/tabular'
Plugin 'scrooloose/nerdtree'
Plugin 'tpope/vim-surround'
Plugin 'wikitopian/hardmode'
Plugin 'tpope/vim-projectionist'
" css
Plugin 'hail2u/vim-css3-syntax'
Plugin 'groenewege/vim-less'
" GIT
Plugin 'tpope/vim-fugitive'
" Elixir/Erlang
Plugin 'elixir-lang/vim-elixir'
Plugin 'avdgaag/vim-phoenix'

" All of your Plugins must be added before the following line
call vundle#end()            " required

filetype plugin indent on " required!

" -----------------------
" BASIC VIM CONFIGURATION
" -----------------------

" Plugins used:
" rails, autoclose, endwise

filetype on  " Automatically detect file types.
set nocompatible
set nobackup
syntax enable

" Formatting (some of these are for coding in C and C++)
set ts=2  " Tabs are 2 spaces
set bs=2  " Backspace over everything in insert mode
set shiftwidth=2  " Tabs under smart indent
set autoindent
set smarttab
set expandtab
set nocp incsearch
set cinwords=if,else,while,do,for,switch,case

set ruler  " Ruler on
set nu  " Line numbers on
set nowrap  " Line wrapping off

" Visual
set showmatch  " Show matching brackets.

set ai " Automatically set the indent of a new line (local to buffer)
set si " smartindent (local to buffer)

if has("autocmd")
  filetype indent on
endif

let mapleader = ","

" http://stackoverflow.com/questions/1327978/sorting-words-not-lines-in-vim
vnoremap <Leader>sl d:execute 'normal i' . join(sort(split(getreg('"'))), ' ')<CR>

" http://vimcasts.org/episodes/tidying-whitespace/"
function! <SID>StripTrailingWhitespaces()
  " Preparation: save last search, and cursor position.
  let _s=@/
  let l = line(".")
  let c = col(".")
  " Do the business:
  %s/\s\+$//e
  " Clean up: restore previous search history, and cursor position
  let @/=_s
  call cursor(l, c)
endfunction
autocmd BufWritePre *.rb,*.erb,*.py,*.js,*.es6,*.haml,*.coffee,*.rake,*.md,*.ex,*.exs,*.eex :call <SID>StripTrailingWhitespaces()

autocmd FileType javascript setlocal shiftwidth=4 tabstop=4
autocmd BufRead *.es6 set filetype=javascript

" -------------------------------------------------
" Ruby TDD related stuff
function! RSpecCurrent()
  execute("!rspec " . expand("%p") . ":" . line("."))
endfunction

function! RSpecSpring()
  execute("!spring rspec " . expand("%p"))
endfunction

function! RSpecSpringLine()
  execute("!spring rspec " . expand("%p") . ":" . line("."))
endfunction

" TODO: check if it needs to be run with rspec or ruby -Itest
map <Leader>t :w\|:!rspec %<CR>
" mt, think 'minitest'
map <Leader>mt :w\|:!ruby -Itest %<CR>

map <Leader>T :call RSpecCurrent()<CR>
map <Leader>sr :call RSpecSpring()<CR>
map <Leader>SR :call RSpecSpringLine()<CR>

" et, think 'elixir test'
map <Leader>et :w\|:Mix test %<CR>

let g:rails_projections = {
      \  "app/services/*.rb": {
      \    "command": "service",
      \    "template": "class %S\nend",
      \    "test": [ "spec/services/%s_spec.rb" ],
      \    "alternate": "spec/services/%s_spec.rb" ,
      \    "affinity": "model"
      \  },
      \  "app/middleware/*.rb": {
      \    "command": "middleware",
      \    "template":
      \      "class %S < Struct.new(:app)\n\n  def call(env)\n    app.call(env)\n  end\n\nend",
      \      "test": [
      \        "spec/middleware/%s_spec.rb"
      \      ]
      \  },
      \  "app/presenters/*.rb": {
      \    "command": "presenter",
      \    "template": "class %S < BasePresenter\nend",
      \    "test": [ "spec/presenters/%s_spec.rb" ],
      \    "affinity": "model"
      \  },
      \  "lib/base_presenter.rb": {"command": "presenter"},
      \  "spec/services/*_spec.rb": {
      \    "command": "servicetest",
      \    "template":
      \      "RSpec.describe %S do\n\n  describe \"its constructor\" do\n    pending 'FIXME: implement this example'\n  end\n\nend",
      \    "alternate": "app/services/%s.rb",
      \    "keywords": "describe context subject skip pending"
      \  }
      \}

" -------------------------------------------------

" TODO move customisation into carpschool colorscheme
colorscheme carpschool
set colorcolumn=233
hi ColorColumn ctermfg=NONE ctermbg=234 cterm=NONE
hi TabLineFill ctermfg=Black ctermbg=White
hi TabLine ctermfg=LightBlue ctermbg=Black
hi TabLineSel ctermfg=White ctermbg=Blue

map <Leader>h <Esc>:call ToggleHardMode()<CR>

map <Leader>r :w\|:!ruby %<CR>
map <Leader>gs :Gstatus<CR>

" repeat last command for visual selection by pressing .
xnoremap . :norm.<CR>

" OS X has modelines disabled by default?
set modelines=5

" I keep typing :W when I meant :w
cnoreabbrev <expr> W getcmdtype()==':'&&getcmdline()=~#'^W'?'w':'W'
